name: Generate Frontend Artifacts

on:
  workflow_run:
    workflows: ["SMU Facility Booking Scraper"]  
    types:
      - completed
  workflow_dispatch: 

jobs:
  run-generate-py:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13.5
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Run generate.py
        run: cd frontend && python generate.py

      - name: Configure git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit index.html if changed
        run: |
          git add index.html
          git diff --cached --quiet || git commit -m "Auto-update index.html [skip ci]"

      - name: Push changes to repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
